//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartServiceweb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddBlogs
    {
        public int BlogId { get; set; }
        public int UserID { get; set; }
        public int CategoryID { get; set; }
        public string textContent { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int PrivacyID { get; set; }
        public string UserLikes { get; set; }
    }
}
