//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartServiceweb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogComments
    {
        public int CommentId { get; set; }
        public int BlogId { get; set; }
        public string Comment { get; set; }
        public int UserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
