//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartServiceweb.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GmContext : DbContext
    {
        public GmContext()
            : base("name=GmContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AddBlogs> AddBlogs { get; set; }
        public virtual DbSet<BlogComments> BlogComments { get; set; }
        public virtual DbSet<BlogDocuments> BlogDocuments { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<FileSettings> FileSettings { get; set; }
        public virtual DbSet<PrivacyType> PrivacyType { get; set; }
        public virtual DbSet<UserRegister> UserRegister { get; set; }
    }
}
