//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartServiceweb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivacyType
    {
        public int PrivacyID { get; set; }
        public string PrivacyTypeName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int PrivacyOrderBy { get; set; }
    }
}
